### ISSUE TITLE
Not downloading videos / Highly throttled downloads - yt-dlp workaround solution

### ISSUE THREAD

**Issue by Jugrnot** [w0d4/yt-backup#48]
Over the last month I've noticed that despite youtube-dl being the most current prod version, even running the cmd manually on a fresh install, youtube seems to have figured out how to highly throttle downloads to a few kb/sec which can drag out video downloads to 4+ hours each.  Obviously this is less than ideal.

Through some research, it appears that youtube-dl doesn't seem to be actively developed at the current time.  There is an alternate fork under the name of "yt-dlp" which is in active development, uses the same command and flag structure, and has resolved the throttled download issue.  https://github.com/yt-dlp/yt-dlp

Install yt-dlp and dependencies, then update your config.json for w0d4's awesome script to point to the binary for yt-dlp:

  "youtube-dl": {
    "binary_path": "/home/jugrnot/.local/bin/yt-dlp",

Save and run as standard:  'python3 yt-backup.py run'

I **really** like this backup project to snag videos daily that my favorite channels post so I can watch them on my plex server and am quite excited to have restored full functionality to this project.  Hopefully sharing this helps the community continue to enjoy w0d4's hard work!

**Comment by oneandonlyjason** [comment]
I've been following the topic for a while now and was wondering if I should test if yt-dlp works together with the script. Since I had seen that the output is at least partially different I did not know if it works. 

So thank you for testing it for everyone else !

But I would suggest to rename the title a little bit to make it clear that you have a solution here and not a question.

**Comment by Jugrnot** [comment]
> I've been following the topic for a while now and was wondering if I should test if yt-dlp works together with the script. Since I had seen that the output is at least partially different I did not know if it works.
> 
> So thank you for testing it for everyone else !
> 
> But I would suggest to rename the title a little bit to make it clear that you have a solution here and not a question.

Thanks a lot for the feedback.  I wanted to tag it with workaround or something like that, but I'm kinda new to adding issues and things in github and couldn't find the best way to do it.  Updated the title with workaround info, hopefully more people find this useful!  

Several days later and we're still going strong, having updated nothing but the binary location for the yt-dlp bin in config.json.

**Comment by oneandonlyjason** [comment]
Do you have Problems with the Resolution sometimes? Sometimes the Script does say it downloaded a Video with 0 Size and Resolution. It does seem to doesnt find the Correct Resolution sometimes. I dont really know if this has something to do with YT-DLP or that something in Python itself changed. 

[See this Picture as Reference](https://push.jason-m.net/2kRMOCU7Uv.jpg)

Edit: It seems like that he sometimes tries to read the Wrong File since switching to YT-DLP

`2021-10-31 15:45:03,302 - yt-backup - ERROR - Could not find video size for video /root/tmp/youtube-dl/mucki_tv/20210323/PODCAST - LIFE OF A LIVESTREAMER - Tipps und Erfahrungen zum Thema Streamen (feat. FalkThemUp)/PODCAST - LIFE OF A LIVESTREAMER - Tipps und Erfahrungen zum Thema Streamen (feat. FalkThemUp) - [1920x1080].en.vtt`

There are only ytdl.part Files in the Directory. So it seems like sometimes when YT-DLP Fails to finish a Download he grabs the Wrong File to read instead of throwing a Error

**Comment by w0d4** [comment]
I'm currently looking into this. I'm trying to download the whole channel which is causing the problems.

**Comment by w0d4** [comment]
Hi @oneandonlyjason ,
I found something out regarding this.
I backed up the complete channel with yt-dlp and had around 9 videos which where not working and had a size of 0 and the .part extension.
I changed my config.json file, to use another video quality.
The video quality string in config.json was intended for youtube-dl, since they have a few problems with choosing best video quality.
This should be fixed, so I changed it to 
`"video-format": "bestvideo*+bestaudio/best"`
I dropped my test DB and downloaded the whole channel again without any problems on any video.
Maybe you can try the config change to go with yt-dlp.
Nevertheless, I'm planning to implement a change, which will check for .part files in working dir after download and force redownload of the video in the next run.

**Comment by oneandonlyjason** [comment]
@w0d4 
> Nevertheless, I'm planning to implement a change, which will check for .part files in working dir after download and force redownload of the video in the next run.

Good to know. Will probably try it when i have Time later. Please let me know when the Check is implemented

**Comment by oneandonlyjason** [comment]
@w0d4 Sadly i still get the same Error even with "video-format": "bestvideo*+bestaudio/best"

**Comment by Jugrnot** [comment]
Biscuits.  I forgot to follow up on this.

Thus far since switching from youtube-dl to ytdlp in w0d4's python script, I've only seen one instance where something with the video resolution made it unplayable in plex, yet works fine via VLC.  Plex refuses to even start playing the video with some error - something about direct play isn't available or enabled.

Oddly, I get that more frequently when I manually downlaod a video using the full command line with bestvideo+bestaudio, and usually seems to be some 4k or higher res videos.  Run yt-dlp with the -F command, identify a 1080 video and audio track seems to rectify that most of the time.

**Comment by oneandonlyjason** [comment]
The Problem is that Youtube is really really unreliable for Videos that dont have as much Views. Mostly because the Videos take a little Time to get Transfered to the CDN when they are not Hot Stored anymore. Which makes Sense for YT because they can store Videos a lot cheaper outside of Germany (where i live) but need them to be transfered to a CDN PoP in my Area for Playback because otherwhise it would need to Buffer all the Time. And this transfer needs time. Sometimes you get HTTP Errors from YT. Like a not Found or a Service Unavaible Error. And it seems that YT-DLP doesnt wait long enough betweeen the Retries. When i test it in Command Line YT-DLP retries all 10 Tries in around 2 Seconds. When i wait a little bit after the Failed download and start it again it can download normally.

> 2022-01-04 14:03:50,569 - yt-backup - DEBUG - Current line: [download]   6.5% of ~139.98MiB at  3.90MiB/s ETA 00:41 (frag 18/275)[download] Got server HTTP error HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10) ...
2022-01-04 14:03:50,569 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10) ..                                                                                    .
2022-01-04 14:03:50,569 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10) ..                                                                                    .
2022-01-04 14:03:50,569 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10) ..                                                                                    .
2022-01-04 14:03:50,569 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10) ..                                                                                    .
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10) ..                                                                                    .
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10) ..                                                                                    .
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10) ..                                                                                    .
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10) ..                                                                                    .
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10) .                                                                                    ..
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [youtube] p_CM_6vr5KM: Downloading webpage
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [youtube] p_CM_6vr5KM: Downloading android player API JSON
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [youtube] p_CM_6vr5KM: Downloading MPD manifest
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [youtube] p_CM_6vr5KM: Downloading MPD manifest
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [info] p_CM_6vr5KM: Downloading 1 format(s): 303+251
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [info] Writing video subtitles to: /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Current line: [download] Destination: /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Found name in line: [download] Destination: /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Parsed downloaded file /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt from youtube-dl output.
2022-01-04 14:03:50,570 - yt-backup - DEBUG - Video name is /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAME                                                                                    R (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt
2022-01-04 14:03:50,581 - yt-backup - ERROR - Could not find video size for video /HDDs/tmp/youtube-dl/mucki_tv/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent/SCHLAG DEN STREAMER (QUIZ) #6 mit Sapaha & Mr27Cent.en.vtt
2022-01-04 14:03:50,581 - yt-backup - DEBUG - Video runtime was set to None seconds
2022-01-04 14:03:50,592 - yt-backup - DEBUG - Video resolution was set to
2022-01-04 14:03:50,593 - yt-backup - DEBUG - Video size was set to 138802 bytes
2022-01-04 14:03:50,601 - yt-backup - INFO - Video p_CM_6vr5KM is downloaded.

In this Case the Script need to see that the Download didnt finish and need to try it again in a next run so it can catch up the Video hopefully sucessfull on the next run

**Comment by w0d4** [comment]
I have updated the script to work around this problem.
I tested it on my side and it's working fine.
If resolution and runtime is None, I expect the video file to be corrupt. The video will not be uploaded to rclone target and the downloaded flag will stay on 0. So, the video will be redownloaded in the next run.
See commit 949a8a1a6a6e24ba172c3872d2f854f8f2cd2389
I also merged the channel_country feature branch into this.

**Comment by oneandonlyjason** [comment]
@w0d4 Thanks will try it later

**Comment by w0d4** [comment]
> @w0d4 Thanks will try it later

How is it working? I have it running since 24h now and cannot see any issues until now.
I had one failed video with .tmp file in working dir. But the video status is now still not downloaded.

**Comment by oneandonlyjason** [comment]
> How is it working? I have it running since 24h now and cannot see any issues until now. I had one failed video with .tmp file in working dir. But the video status is now still not downloaded.

Had sadly no Time yet because some stuff was happening yesterday.
Will try to have some time this evening

**Comment by oneandonlyjason** [comment]
> Traceback (most recent call last):
  File "/root/yt_backup/yt-backup.py", line 1798, in <module>
    add_channel(channel_id)
  File "/root/yt_backup/yt-backup.py", line 539, in add_channel
    channel_name_and_country = get_channel_name_from_google(local_channel_id)
NameError: name 'get_channel_name_from_google' is not defined

Is there a new dependency?

**Comment by w0d4** [comment]
No, no new dependency, but I think I have done something wrong while merging two branches.
This should be fixed in bc83f09

**Comment by oneandonlyjason** [comment]
Yeah now the Script works again. I couldnt test your Download Error Change right now because this time it downloaded every Video on the First try .-. But this should generally fix it i think

**Comment by oneandonlyjason** [comment]
I also write this here to Document this (i send you a PM also @w0d4). With the Country Feature in Place the Script doesnt handle it correctly when a Channel has no Public Country Information. You cant add Channels that dont have this Information Public. The Script simply says that the Channel could not be Found on Youtube

>  try:
        channel_name = str(response["items"][0]["brandingSettings"]["channel"]["title"])
        channel_country = str(response["items"][0]["brandingSettings"]["channel"]["country"])
    except KeyError:
        logger.error("No channel with this id could be found on youtube.")
        return None

Seems like it Just tries to get both and if one of them Fails it simply says that the Channel does not exist. But there are Channels without this Information Public so for them it will always fail

**Comment by w0d4** [comment]
I think I fixed this error in 8231833
I found two channels without origin country information and it worked for them.

**Comment by oneandonlyjason** [comment]
I was able to add a Channel that didnt worked before to the Database, will try if it downloads everything correctly which it probably does
